# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-01-05 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'zichanjilubiao',
            },
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='yewuxian')),
            ],
            options={
                'verbose_name_plural': 'yewuxianbiao',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=16, verbose_name='chachaowei')),
                ('model', models.CharField(max_length=32, verbose_name='yinpanxinghao')),
                ('capacity', models.FloatField(verbose_name='cipanrongliangGB')),
                ('pd_type', models.CharField(max_length=32, verbose_name='cipanleixing')),
            ],
            options={
                'verbose_name_plural': 'Diskbiao',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'cuowurizhibiao',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='jifang')),
                ('floor', models.CharField(default=1, max_length=16, verbose_name='loucheng')),
            ],
            options={
                'verbose_name_plural': 'IDCbiao',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=32, verbose_name='chachaowei')),
                ('manufacturer', models.CharField(blank=True, max_length=32, null=True, verbose_name='zhizhaoshang')),
                ('model', models.CharField(max_length=32, verbose_name='xinghao')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='rongliang')),
                ('sn', models.CharField(blank=True, max_length=16, null=True, verbose_name='neicunsn')),
                ('speed', models.CharField(blank=True, max_length=16, null=True, verbose_name='speed')),
            ],
            options={
                'verbose_name_plural': 'Memorybiao',
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='wangkamingcheng')),
                ('hwaddr', models.CharField(max_length=64, verbose_name='wangkamacdizhi')),
                ('netmask', models.CharField(max_length=32)),
                ('ipaddrs', models.CharField(max_length=64, verbose_name='ipdizhi')),
                ('up', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'NICbiao',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_status_id', models.IntegerField(choices=[(1, 'shangjia'), (2, 'online'), (3, 'offline'), (4, 'xiajia')], default=1, verbose_name='zhuangtai')),
                ('cabinet_num', models.CharField(blank=True, max_length=32, null=True, verbose_name='jiguihao')),
                ('cabinet_order', models.CharField(blank=True, max_length=32, null=True, verbose_name='jiguizhongxuhao')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='zhujiming')),
                ('os_platform', models.CharField(blank=True, max_length=32, null=True, verbose_name='system')),
                ('os_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='systemversion')),
                ('sn', models.CharField(db_index=True, max_length=32, verbose_name='snnum')),
                ('manufacturer', models.CharField(blank=True, max_length=32, null=True, verbose_name='zhizhaoshang')),
                ('model', models.CharField(blank=True, max_length=32, null=True, verbose_name='xinghao')),
                ('cpu_count', models.IntegerField(blank=True, null=True, verbose_name='CPUgeshu')),
                ('cpu_physical_count', models.IntegerField(blank=True, null=True, verbose_name='CPUwuligeshu')),
                ('cpu_model', models.CharField(blank=True, max_length=128, null=True, verbose_name='CPUxinghao')),
                ('latest_date', models.DateField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.BusinessUnit', verbose_name='shuyudeyewuxian')),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.IDC', verbose_name='IDCjifang')),
            ],
            options={
                'verbose_name_plural': 'fuwuqibiao',
            },
        ),
        migrations.AddField(
            model_name='nic',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nic_list', to='api.Server'),
        ),
        migrations.AddField(
            model_name='memory',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_list', to='api.Server'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Server'),
        ),
        migrations.AddField(
            model_name='disk',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk_list', to='api.Server', verbose_name='fuwuqi'),
        ),
        migrations.AddField(
            model_name='assetrecord',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='api.Server'),
        ),
    ]
